[In progress] Add license feature
ros/rospack pull request #56
Opened 2016-01-06 01:11 UTC by 130s

I open a PR to ask for comments although work is in progress.
I'm adding a command that returns the license of the dependency of a package.

The example looks as the following (I know this needs lots of polish):

```
$ rospack depends1 navfn
costmap_2d
geometry_msgs
nav_core
nav_msgs
pcl_conversions
pcl_ros
pluginlib
rosconsole
roscpp
tf
visualization_msgs

$ rospack license navfn
costmap_2d	BSD 
geometry_msgs	BSD 
nav_core	BSD 
nav_msgs	BSD 
pcl_conversions	BSD 
pcl_ros	BSD 
pluginlib	BSD Boost Software License 
rosconsole	BSD 
roscpp	BSD 
tf	BSD 
visualization_msgs	BSD 
```

Below is just my note.

Requirement
- Implemented as upstream as possible --> so `rospack` should be a good place?
- Multi-platform, not just on Ubuntu  --> Need ROS/Catkin specific tool that can handle `package.xml` where the license is declared?
- Must work with all ROS packages whether it's deb or source.
- Make it as both 1) public API and 2) commandline option.
- No breakage for existing api.

Research for existing tools
- `debtree`: Great tool for speculating pkg dependency, with commanline output and even GUi output. We can aim its output.
- `ldd`: Only works with libs.
- `Dependency Walker`: Only works on MS Windows.
- `binscan`: only works for binaries.
- `ELF Library Viewer`: only works for ELF executables.

2016-01-06 01:26 UTC, 130s commented
Better sample output to show this kind of command might be useful:

```
$ rospack depends1 gmapping
nav_msgs
openslam_gmapping
roscpp
tf

$ rospack license gmapping
nav_msgs	BSD 
openslam_gmapping	CreativeCommons-by-nc-sa-2.0 
roscpp	BSD 
tf	BSD 
```

2016-01-06 06:20 UTC, dirk-thomas commented
Maybe an option to the `depend*` verbs would be better then a new verb?

2016-01-06 07:56 UTC, tfoote commented
This looks useful. I agree that the option to the depend* commands might provide more flexibility for the user if they want the full recursion or not. Something like --show-license

2016-03-01 00:43 UTC, dirk-thomas commented
I marked this with the milestone "untargeted" until there is any update.

2016-12-31 09:43 UTC, 130s commented
I'm back to this and pushed a working code that includes the suggested change. 
Output example with the current code is attached below.

But then I realized that some changes to `Rosstackage` class (separately opened #65, #66) will make writing client codes much easier and more flexible. Though there's a room for improving the output, I'll wait if they get to be merged before I add further change to this PR.

The PRs listed above are against the latest branch `jade-devel` so either way I'll have to open a new PR for adding license feature to jade-devel anyway.

```
$ rospack depends --license gmapping
actionlib BSD
actionlib_msgs BSD
catkin BSD
cpp_common BSD
gencpp BSD
genlisp BSD
genmsg BSD
genpy BSD
geometry_msgs BSD
message_filters BSD
message_generation BSD
message_runtime BSD
nav_msgs BSD
openslam_gmapping CreativeCommons-by-nc-sa-2.0
rosbag BSD
rosbag_storage BSD
rosbuild BSD
rosclean BSD
rosconsole BSD
roscpp BSD
roscpp_serialization BSD
roscpp_traits BSD
rosgraph BSD
rosgraph_msgs BSD
roslaunch BSD
roslib BSD
roslz4 BSD
rosmaster BSD
rosmsg BSD
rosnode BSD
rosout BSD
rospack BSD
rosparam BSD
rospy BSD
rosservice BSD
rostest BSD
rostime BSD
rostopic BSD
rosunit BSD
roswtf BSD
sensor_msgs BSD
std_msgs BSD
tf BSD
tf2 BSD
tf2_msgs BSD
tf2_py BSD
tf2_ros BSD
topic_tools BSD
xmlrpcpp LGPL-2.1
```

Some possible changes for the output:
- Grouping per license and package.
- Indentation and other minor cosmetics.

2017-01-25 18:42 UTC, dirk-thomas commented on src/rospack_cmdline.cpp
> +	 (command == "list-duplicates"))
Please remove white space changes like this.

2017-01-25 18:42 UTC, dirk-thomas commented on src/rospack_cmdline.cpp
> +          output.append("[--length=<length>] [--zombie-only]\n\nForce a full crawl of package directories and report the directories that took the longest time to crawl.\n\n--length=N how many direct
Please revert the indentation change.

2017-01-25 18:44 UTC, dirk-thomas commented on src/rospack_cmdline.cpp
> +    }
Please use consistent indentation matching the existing code.

2017-01-25 18:44 UTC, dirk-thomas commented on src/rospack.cpp
> +    //	printf("DEBUG 128\n");
Please remove.

2017-01-25 18:44 UTC, dirk-thomas commented on src/rospack.cpp
> +    }
Please avoid unrelated changes like this.

2017-01-25 18:45 UTC, dirk-thomas commented on src/rospack.cpp
> +      //      (in the case of multiple-license).
This TODO should be addressed before this is merged.

2017-01-25 18:45 UTC, dirk-thomas commented on src/rospack.cpp
> +    //printf("DEBUG) pkg_name to find: %s\n", pkg_name.c_str());
Please remove debugging comments.

2017-01-25 18:45 UTC, dirk-thomas commented on src/rospack.cpp
> +    //std::pair<std::string, std::vector<std::string> > dep_name_licenses;
Please remove debugging comments.

2017-01-25 18:46 UTC, dirk-thomas commented on include/rospack/rospack.h
> +    void licenses(std::vector<std::string>& deps, std::set<std::pair<std::string, std::vector<std::string> > >& licenses);
This will change ABI which needs to be considered when  deciding into which branch to merge this.

2017-01-25 18:46 UTC, dirk-thomas requested changes
What is the status of this PR and the relationship to #66.

2017-02-25 10:31 UTC, 130s commented
Sorry for the delay. Beside that I haven't addressed inline comments, I'm slowly working on other PRs that ideally I would like this PR to depend on. Some of which got merged in but some may not because of abi breakage each PR introduces. Anyways, once all those PRs either get merged or closed, I'll update this PR. 

At minimum, I can update this PR to not depend on any of those PRs, to be merge-able by itself (including https://github.com/ros/rospack/pull/56#discussion_r97849395 that breaks abi). I really want this license feature to be added to Indigo given its large user base.

2017-02-25 15:26 UTC, dirk-thomas commented
Please describe the full picture you have in mind referencing all existing PR as well as describe the ones you plan to make in the future. This will allow others to comment on / review the big picture.

2017-03-02 00:45 UTC, 130s commented on include/rospack/rospack.h
> +    void licenses(std::vector<std::string>& deps, std::set<std::pair<std::string, std::vector<std::string> > >& licenses);
So, this one doesn't change ABI I think. I ran abi compatibility check against the current DEB and the one compiled using this PR.

![abicc_librospack_indigo_2 2 7_with_2 2 8-1](https://cloud.githubusercontent.com/assets/1840401/23487772/1db96094-fe9d-11e6-96d7-cbe66ee9948d.png)

```
$ dpkg -p ros-indigo-rospack|grep Ver
Version: 2.2.7-0trusty-20160627-160632-0700
```
```
$ git log     
commit 5af0cc2a3d36f14a9de450ac28dbe9c89704dad8
Author: Isaac I.Y. Saito <130s@2000.jukuin.keio.ac.jp>
Date:   Sat Feb 6 15:33:44 2016 -0800

    Add license feature
$  catkin b rospack --no-deps
```

2017-03-02 00:58 UTC, 130s commented
All comments but one (for abi compatibility) are addressed.

- This PR by itself can be review-merge IMO.
- Ideally, however, depending on https://github.com/ros/rospack/pull/71 (needs backported to indigo) and https://github.com/ros/rospack/pull/69 will be better because the amount of custom code in this PR can be less with them.

2017-03-02 20:53 UTC, dirk-thomas commented
My previous question is still pending:

> Please describe the full picture you have in mind referencing all existing PR as well as describe the ones you plan to make in the future. This will allow others to comment on / review the big picture.

2017-05-22 22:30 UTC, dirk-thomas commented
I will close this for now due to lack of response. Please feel free to comment with the requested information and I am happy to reopen this.

2017-05-22 22:30 UTC, closed without merging

2017-08-09 06:22 UTC, jitrc commented
https://github.com/ros/rospack/pull/76